services:
  develop:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: develop
    hostname: develop
    command: ["/bin/bash", "-c", "tail -f /dev/null"]

    volumes:
      - .:/home/vscode                      # Source Code Repository
      - vespa-logs:/opt/vespa/logs:ro       # Vespa Logs
    networks:
      - container-network